[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y ffmpeg python3-pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Building completed'"
]

[start]
cmd = "python bot.py"